---
# Install Docker on Ubuntu Bionic/Xenial

- name: ensure old versions of docker are uninstalled
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: update required packages to latest version
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add docker public gpg key to apt keyring
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: get ubuntu release name
  command: lsb_release -cs
  register: release_command


- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release_command.stdout }} stable
    state: present

- name: install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: create docker services directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    group: docker
    owner: "{{ ansible_user }}"
  with_items:
    - /docker
    - /docker/services
